name: Test and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  default:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
      - name: Install dependencies
        run: |
          npm ci
          npm install --global @salesforce/cli
      - name: Run tests
        run: npm run test
      - name: Run E2E tests
        env:
          SFDX_AUTH_URL_DEVHUB: ${{ secrets.SFDX_AUTH_URL_DEVHUB }}
        run: |
          echo "${SFDX_AUTH_URL_DEVHUB}" | sf org login sfdx-url --set-default-dev-hub --alias devhub --sfdx-url-stdin
          sf org create scratch -f config/project-scratch-def.json --set-default
          npm run test:e2e
      - name: Delete scratch org
        if: always()
        run: |
          sf org delete scratch --no-prompt
      - name: Release package
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
